base_url = "https://t3kla.github.io"

title = "T3kla"
description = "A random place for random thoughts"
author = "Manuel"
default_language = "en"

output_dir = "public"

minify_html = false
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]